{% set ver = "6.4.0" %}
{% set beta = "beta20170207" %}
{% set version = ver + "_" + beta %}
{% set commit = "84b636d8883db5ab3f4a9619d3c8a4f374b99343" %}

package:
  name: ncl
  version: {{ version }}

source:
    fn: {{ commit }}.tar.gz
    url: https://github.com/NCAR/ncl/archive/{{ commit }}.tar.gz
    sha256: 58084188f1e1cb043b4979ea85f1b070c16eafb9b64225b5aed1966a1447577d

build:
    number: 0
    skip: True  # [win]
    detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc
    - libnetcdf 4.4.*
    - proj4 4.9.3
    - gdal 2.1.*
    - hdfeos2
    - hdfeos5
    - jasper
    - libpng >=1.6.28,<1.7
    - jpeg 9*
    - zlib 1.2.*
    - hdf4
    - hdf5 1.8.17|1.8.17.*
    - libiconv
    - curl
    - cairo 1.14.*  # [linux]
    - freetype 2.7|2.7.*  # [linux]
    - udunits2
    - bzip2 1.0.*
    - gsl
    - pkg-config
    - pixman 0.34.*
  run:
    - libgcc
    - libnetcdf 4.4.*
    - hdf4
    - proj4 4.9.3
    - gdal 2.1.*
    - hdfeos2
    - hdfeos5
    - jasper
    - libpng >=1.6.28,<1.7
    - jpeg 9*
    - zlib 1.2.*
    - hdf4
    - hdf5 1.8.17|1.8.17.*
    - libiconv
    - curl
    - cairo 1.14.*  # [linux]
    - freetype 2.7|2.7.*  # [linux]
    - udunits2
    - bzip2 1.0.*
    - gsl
    - pixman 0.34.*
    - esmf

test:
    commands:
        - test "$(ncl -V)" = "{{ version }}"
        - NCARG_ROOT=${PREFIX} ${RECIPE_DIR}/check_files | grep -qv '^<'

about:
  home: http://ncl.ucar.edu/
  license: 'NCL Source Code'
  summary: 'NCAR Command Language'

extra:
  recipe-maintainers:
    - khallock
    - marylhaley
    - david-ian-brown
    - ocefpaf
